# Generated by Django 4.1.3 on 2022-12-20 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': [('add_permission_to_role', 'Can add permissions to Roles'), ('remove_permission_to_role', 'Can remove permissions to Roles')]},
        ),
    ]
