# Generated by Django 4.1.3 on 2022-12-27 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_role_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': [('add_permission_to_role', 'Can add permissions to Roles'), ('remove_permission_to_role', 'Can remove permissions to Roles'), ('add_role_to_user', 'Can add role to users')]},
        ),
    ]
