# Generated by Django 4.1.3 on 2023-03-11 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_role_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': [('add_permission_to_role', 'Can add permissions to Roles'), ('remove_permission_to_role', 'Can remove permissions to Roles'), ('add_role_to_user', 'Can add role to users'), ('remove_role_to_use', 'Can remove role to users')]},
        ),
    ]
