# Generated by Django 4.1.3 on 2023-05-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransferdocument',
            name='receiving_warehouse_modified_items',
            field=models.ManyToManyField(related_name='stock_transfer_received', to='stock.stockmodificationdocument'),
        ),
        migrations.AlterField(
            model_name='stocktransferdocument',
            name='sender_warehouse_modified_items',
            field=models.ManyToManyField(related_name='stock_transfer_send', to='stock.stockmodificationdocument'),
        ),
    ]
