runtime: custom
env: flex
env_variables:
  SECRET_KEY: "super_secret_key"
  ALLOWED_HOSTS: "storefront-365900.uc.r.appspot.com"
  DEBUG: "False"
  CORS_ALLOWED_ORIGINS: "https://frontend-dot-storefront-365900.uc.r.appspot.com"

beta_settings:
  cloud_sql_instances: storefront-365900:us-central1:storefront=tcp:5432
