# Generated by Django 4.1.3 on 2023-05-24 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0013_rename_itemgroup_itemcategory'),
        ('company', '0001_initial'),
        ('stock', '0002_alter_stocktransferdocument_receiving_warehouse_modified_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(null=True)),
                ('cost_calculated', models.FloatField()),
                ('is_paid', models.BooleanField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.distributor')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.paymentmethod')),
                ('purchased_items', models.ManyToManyField(to='stock.stockmodificationdocument')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
