# Generated by Django 4.0.4 on 2022-05-16 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255, unique=True)),
                ('is_service', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=48)),
                ('cost', models.FloatField()),
                ('markup', models.FloatField()),
                ('root_product',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_versions',
                                   to='inventory.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='current_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='inventory.productdetail'),
        ),
        migrations.CreateModel(
            name='ModifyStockDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('quantity_modified', models.FloatField()),
                ('product_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_changes',
                                   to='inventory.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LostAndDamagedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('type_of_doc', models.CharField(choices=[('LST', 'Lost'), ('DMD', 'Damaged')], max_length=3)),
                ('lost_products', models.ManyToManyField(to='inventory.modifystockdocument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('modified_products', models.ManyToManyField(to='inventory.modifystockdocument')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
