# Generated by Django 4.0.5 on 2022-06-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdetail',
            name='sku',
        ),
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
