# Generated by Django 4.0.4 on 2022-05-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='is_service',
            field=models.BooleanField(default=False),
        ),
    ]
