# Generated by Django 4.0.4 on 2022-05-26 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_productdetail_is_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_service',
        ),
    ]
