# Generated by Django 4.0.6 on 2022-08-27 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_item_barcode_item_cost_item_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='current_detail',
        ),
        migrations.DeleteModel(
            name='ItemDetail',
        ),
    ]
