# Generated by Django 4.2.1 on 2023-06-05 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('inventory', '0006_alter_itemcategory_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRecountDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.document')),
            ],
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_amount', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventory.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovementAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification_amount', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('item_cost', models.FloatField(blank=True)),
                ('item_markup', models.FloatField(blank=True)),
                ('item_price', models.FloatField(blank=True)),
                ('modification_cost_value', models.FloatField(blank=True)),
                ('modification_price_value', models.FloatField(blank=True)),
                ('creation_date', models.DateTimeField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.item')),
                ('parent_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='documents.document')),
            ],
        ),
    ]
