# Generated by Django 4.1.2 on 2022-11-12 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_item_barcode_alter_item_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='distributoritemoffer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='distributoritemoffer',
            name='distributor',
        ),
        migrations.RemoveField(
            model_name='distributoritemoffer',
            name='item',
        ),
        migrations.RemoveField(
            model_name='inventorydocument',
            name='items',
        ),
        migrations.RemoveField(
            model_name='modifystockorder',
            name='item',
        ),
        migrations.RemoveField(
            model_name='purchasedocument',
            name='distributor',
        ),
        migrations.RemoveField(
            model_name='purchasedocument',
            name='items',
        ),
        migrations.RemoveField(
            model_name='saledocument',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='saledocument',
            name='items',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Distributor',
        ),
        migrations.DeleteModel(
            name='DistributorItemOffer',
        ),
        migrations.DeleteModel(
            name='InventoryDocument',
        ),
        migrations.DeleteModel(
            name='ModifyStockOrder',
        ),
        migrations.DeleteModel(
            name='PurchaseDocument',
        ),
        migrations.DeleteModel(
            name='SaleDocument',
        ),
    ]
