# Generated by Django 4.2.1 on 2023-06-06 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('inventory', '0009_stockmovementaction_is_cumulative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovementaction',
            name='parent_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='documents.document'),
        ),
    ]
