# Generated by Django 4.1.3 on 2022-12-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_distributoritemoffer_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': [('activate_item', 'Can Activate and Deactivate Items')]},
        ),
    ]
