# Generated by Django 4.1.3 on 2023-05-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_item_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=255)),
                ('is_primary_warehouse', models.BooleanField(default=False)),
                ('can_distribute', models.BooleanField(default=True)),
            ],
        ),
    ]
