# Generated by Django 4.1.3 on 2023-05-24 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_client_distributor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemGroup',
            new_name='ItemCategory',
        ),
    ]
