# Generated by Django 4.2.2 on 2023-06-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_transactiondocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondocument',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
