# Generated by Django 4.2.2 on 2023-06-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_transactiondocument_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondocument',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
