# Generated by Django 4.2.2 on 2023-06-12 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_transactiondocument_total'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='document',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='documents.transactiondocument'),
            preserve_default=False,
        ),
    ]
