# Generated by Django 4.2.2 on 2023-06-14 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_transactiondocument_total'),
        ('company', '0003_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='documents.transactiondocument'),
        ),
    ]
