# Generated by Django 4.2.2 on 2023-06-12 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_transactiondocument_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='SaleDocument',
            fields=[
                ('transactiondocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.transactiondocument')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_documents', to='sales.client')),
            ],
            bases=('documents.transactiondocument',),
        ),
    ]
