# Generated by Django 4.2.2 on 2023-06-12 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_transactiondocument_total'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saledocument',
            name='document_ptr',
        ),
        migrations.RemoveField(
            model_name='saledocument',
            name='sale_amount',
        ),
        migrations.AddField(
            model_name='saledocument',
            name='transactiondocument_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.transactiondocument'),
            preserve_default=False,
        ),
    ]
